site_name: OpenWorm
theme: readthedocs
nav:
  - Introduction : index.md
  - Background : background.md
  - History : fullhistory.md
  - Releases : releases.md
  - Modelling : modeling.md
  - Projects:
      - Projects Overview : projects.md
      - Sibernetic : Projects/sibernetic.md
      - Geppetto : Projects/geppetto.md
      - Movement : Projects/worm-movement.md
      - DevoWorm : Projects/DevoWorm.md
      - Optimization : Projects/optimization.md
      - Representation : Projects/datarep.md
      - Community Outreach : Projects/community-proj.md
      - Muscle / Neuron /  Channel : Projects/muscle-neuron-integration.md
  - Community:
      - Community Overview : community.md
      - Github : Community/github.md
      - Repos : Community/repositories.md
      - Membership : Community/membership.md
  - Resources:
      - Resources Overview: Resources/resources.md
      - Running NeuroML connectome: Resources/running-nc.md
  - FAQ : faq.md
