version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6
commands:
  install:
    steps:
      - checkout
      - run:
          name: apt install
          command: |
            sudo apt-get update
            sudo apt-get install -yqq build-essential libxml2-dev zlib1g-dev bison flex
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - dependency-cache-{{ checksum "requirements.txt" }}-
      - run:
          name: Create venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python -m pip install -U pip
            echo "export MAKEFLAGS=\"PYTHON=$(which python) PIP_OPTS=-U\"" >> $BASH_ENV
      - run: make install
      - save_cache:
          key: dependency-cache-{{ checksum "requirements.txt" }}-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - "venv"
  check:
    steps:
      - run: make check
jobs:
  build:
    <<: *defaults
    parameters:
      run-checks:
        type: boolean
        default: true
    steps:
      - install
      - when:
          condition: <<parameters.run-checks>>
          steps:
            - check
      - run: make build
      - store_artifacts:
          path: site
      - deploy:
          name: if master; mkdocs gh-deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              SHA="$(git log -1 --pretty=format:%h)"
              git fetch origin gh-pages:gh-pages
              git config user.name OpenWorm-bot
              git config user.email openworm-bot@noreply.users.github.com
              . venv/bin/activate
              ghp-import -n site
              git checkout gh-pages
              if [[ "$(git diff origin/gh-pages --numstat | grep -v sitemap.xml.gz)" == 1$'\t'1$'\t'index.html ]]; then
                echo "Ignoring sitemap.xml.gz, only one line changed in index.html (assumed timestamp)"
                echo "Skipping already deployed master@$SHA"
              else
                git commit --amend -m "Deploy master@$SHA [ci skip]"
                git remote set-url origin https://${GITHUB_API_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git
                git push -f origin gh-pages
              fi
            fi
workflows:
  version: 2
  test:
    jobs:
      - build
  poll:
    triggers:
      - schedule:
          cron: "0 * * * *"  # every hour
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          run-checks: false
