version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6
commands:
  install:
    steps:
      - checkout
      - run:
          name: apt install
          command: |
            sudo apt-get update
            sudo apt-get install -yqq build-essential libxml2-dev zlib1g-dev bison flex
      - run:
          name: Fix permissions
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - dependency-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - dependency-cache-
      - run:
          # may fix build issues
          name: Ensure pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py
      - run: SKIP_HEADER_INSTALL=1 PIP_OPTS="--user -U" make install
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
  check:
    steps:
      - run: make check
jobs:
  build:
    <<: *defaults
    parameters:
      run-checks:
        type: boolean
        default: true
    steps:
      - install
      - when:
          condition: <<parameters.run-checks>>
          steps:
            - check
      - run: make build
      - store_artifacts:
          path: site
      - deploy:
          name: if master; mkdocs gh-deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git remote set-url origin https://${GITHUB_API_TOKEN}@github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git
              mkdocs gh-deploy -m "Deploy master@{sha} (MkDocs v{version}) [ci skip]" -v
            fi
workflows:
  version: 2
  test:
    jobs:
      - build
  poll:
    triggers:
      - schedule:
          cron: "0 * * * *"  # every hour
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          run-checks: false
