version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6
commands:
  install:
    steps:
      - checkout
      - run:
          name: Fix permissions
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - dependency-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - dependency-cache-
      - run:
          # may fix build issues
          name: Ensure pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py
      - run: pip install -U mkdocs
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
jobs:
  mkdocs:
    <<: *defaults
    steps:
      - install
      - run: mkdocs build
      - store_artifacts:
          path: site
      - deploy:
          name: if master; mkdocs gh-deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdocs gh-deploy -m "Deploy master@{sha} (MkDocs v{version}) [ci skip]" -v
            fi

workflows:
  version: 2
  test:
    jobs:
      - mkdocs
  poll:
    triggers:
      - schedule:
          cron: "0 * * * *"  # every hour
          filters:
            branches:
              only:
                - master
    jobs:
      - mkdocs
