version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6
commands:
  install:
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -yqq build-essential libxml2-dev zlib1g-dev bison flex
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - dependency-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - dependency-cache-
      - run:
          # may fix build issues
          name: Ensure pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py
      - run: SKIP_H_INSTALL=1 make install
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            - "/home/circleci/.cache/pip"
  check:
    steps:
      - run: make check
jobs:
  mkdocs:
    <<: *defaults
    parameters:
      run-checks:
        type: boolean
        default: true
    steps:
      - install
      - when:
          condition: <<parameters.run-checks>>
          steps:
            - check
      - run: make build
      - store_artifacts:
          path: site  # could directly deploy this directory instead?

workflows:
  version: 2
  test:
    jobs:
      - mkdocs
  poll:
    triggers:
      - schedule:
          # every hour
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - mkdocs:
          run-checks: false
