version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6
commands:
  install:
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - dependency-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - dependency-cache-
      - run:
          # may fix build issues
          name: Ensure pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py
      - run: pip install -U mkdocs
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
jobs:
  mkdocs:
    <<: *defaults
    steps:
      - install
      - run: mkdocs build
      - add_ssh_keys:
          # tell CI to use openworm-bot@github's ssh key (for deploy permissions)
          # https://circleci.com/docs/2.0/add-ssh-key/
          fingerprints:
            - "ad:f1:51:b7:68:cb:19:08:b2:7d:63:e3:eb:79:1a:63"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mkdocs gh-deploy
            fi
      - store_artifacts:
          path: site

workflows:
  version: 2
  test:
    jobs:
      - mkdocs:
          filters:
            branches:
              ignore: /^gh-pages/  # no tests exist on deployed pages branch
  poll:
    triggers:
      - schedule:
          cron: "0 * * * *"  # every hour
          filters:
            branches:
              only:
                - master
    jobs:
      - mkdocs
