version: 2.1
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6
commands:
  install:
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          keys:
            - dependency-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
            - dependency-cache-
      - run:
          # may fix build issues
          name: Ensure pip
          command: |
            curl -O https://bootstrap.pypa.io/get-pip.py
            python get-pip.py
      - run: pip install -U -r requirements.txt
      - save_cache:
          key: dependency-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
  check:
    steps:
      - run: black -l 79 --check build.py
      - run: flake8 --count --statistics --show-source build.py
jobs:
  check:
    <<: *defaults
    steps:
      - install
      - check
  mkdocs:
    <<: *defaults
    steps:
      - install
      - run: python build.py
      - run: mkdocs build
      - store_artifacts:
          path: site  # could directly deploy this directory instead?

workflows:
  version: 2
  test:
    jobs:
      - check
      - mkdocs:
          requires:
            - check
  poll:
    triggers:
      - schedule:
          # every hour
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - mkdocs
